apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: python-full-test
  janus-idp.io/tekton: python-full-test
  backstage.io/kubernetes-id: python-full-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python-full-test
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
